# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='老王', max_length=20),
        ),
    ]
