"""empty message

Revision ID: 0a2a128959a1
Revises: b004c6ee1700
Create Date: 2018-10-11 20:52:41.231959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2a128959a1'
down_revision = 'b004c6ee1700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('pwd', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'pwd')
    # ### end Alembic commands ###
