# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
