# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookieApp', '0002_auto_20180918_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='passwd',
            field=models.CharField(max_length=20),
        ),
    ]
