# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='producting',
            new_name='productimg',
        ),
    ]
