# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 02:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_auto_20180927_0207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
