# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.CharField(max_length=32),
        ),
    ]
