"""empty message

Revision ID: 1ea5381dcf6c
Revises: b2c0859d8922
Create Date: 2018-10-05 06:12:13.564673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea5381dcf6c'
down_revision = 'b2c0859d8922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tags', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tags')
    # ### end Alembic commands ###
