# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newday', '0002_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='USermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
    ]
