# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0003_auto_20180914_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='onetomany.UserType'),
        ),
    ]
