# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0004_auto_20180914_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onetomany.UserType'),
        ),
    ]
