# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='书名'),
        ),
    ]
