# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPasswd',
            field=models.CharField(max_length=32),
        ),
    ]
