# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 01:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_cart'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('obj1', django.db.models.manager.Manager()),
            ],
        ),
    ]
