# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_auto_20180927_0221'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
    ]
