# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0013_auto_20180927_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderid',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
