# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0014_auto_20180927_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
