# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(default=18)),
                ('address', models.TextField(default='深圳')),
                ('height', models.FloatField(default=1.8)),
                ('sex', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=2, default=140.23, max_digits=6)),
                ('n', models.NullBooleanField(default=True)),
                ('d', models.DateField()),
                ('img', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
                ('user_type', models.IntegerField(choices=[(1, '青铜'), (2, '白银用户'), (3, '黄金用户'), (4, '铂金用户')], default=1)),
            ],
        ),
    ]
