# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='d',
            field=models.DateField(auto_now=True),
        ),
    ]
