# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
