# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_person_birthday2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='d',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='img',
        ),
        migrations.RemoveField(
            model_name='person',
            name='n',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
    ]
